version: "3"

services:

  graf:
    image: grafana/grafana
    ports:
      - "82:3000"
    volumes:
      - ./graf/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    depends_on:
      - prom
      
  prom:
    image: prom/prometheus:latest
    ports:
      - "81:9090"
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml

  web:
    build: py
    command: python app.py
    ports:
      - "80:5000"
    depends_on:
      - prom
